/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cbra.web.support;

/**
 *
 * @author HUXIAOFENG
 */
public enum MenuSelectionEnum {

    ACCOUNT,
    ACCOUNT_OVERVIEW,
    ACCOUNT_REG_INFO,
    ACCOUNT_MODIFY_PASSWORD,
    ACCOUNT_CONTACTS,
    ACCOUNT_CREDIT_POINT,
    ACCOUNT_SEAL,
    ADDFUND,
    YOOPAY_SERVICE,
    TICKET,
    FUNDCOLLECT,
    FUNDCOLLECT_EVENT,
    FUNDCOLLECT_DONATION,
    FUNDCOLLECT_SERVICE,
    FUNDCOLLECT_PRODUCT,
    FUNDCOLLECT_MEMBER,
    FUNDCOLLECT_CREATE,
    FUNDCOLLECT_EVENT_CREATE,
    FUNDCOLLECT_DONATION_CREATE,
    FUNDCOLLECT_SERVICE_CREATE,
    FUNDCOLLECT_PRODUCT_CREATE,
    FUNDCOLLECT_MEMBER_CREATE,
    FUNDCOLLECT_LIST,
    FUNDCOLLECT_EVENT_LIST,
    FUNDCOLLECT_EVENT_TEMPLATE_LIST,
    FUNDCOLLECT_EVENT_CALENDAR,
    FUNDCOLLECT_DONATION_LIST,
    FUNDCOLLECT_SERVICE_LIST,
    FUNDCOLLECT_PRODUCT_LIST,
    FUNDCOLLECT_MEMBER_LIST,
    FUNDPAYMENT,
    FUNDTRANSFER,
    FUNDWITHDRAW,
    FUNDWITHDRAW_CREATE,
    FUNDWITHDRAW_LIST,
    FUNDWITHDRAW_MANAGER,
    FUNDWITHDRAW_RATE,
    YOOPAY_API,
    YOOPAY_SERVICE_API,
    YOOPAY_SERVICE_API_INVOICE_LIST,
    TRANSACTION,
    TRANSACTION_LIST,
    TRANSACTION_VOLUME_LIST;
}
