<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<div class="two-loc">
    <c:if test="${param.page == '0'}"> <div class="two-loc-c"><fmt:message key="BANNER_当前位置" bundle="${bundle}"/>：<a href="/public/index"><fmt:message key="BANNER_筑誉首页" bundle="${bundle}"/></a> > <fmt:message key="INDEX_资讯专区" bundle="${bundle}"/></div></c:if>
    <c:if test="${param.page == '1'}"><div class="two-loc-c"><fmt:message key="BANNER_当前位置" bundle="${bundle}"/>：<a href="/public/index"><fmt:message key="BANNER_筑誉首页" bundle="${bundle}"/></a> > <fmt:message key="INDEX_走进筑誉" bundle="${bundle}"/> > <fmt:message key="INDEX_筑誉理念" bundle="${bundle}"/></div></c:if>
    <c:if test="${param.page == '2'}"><div class="two-loc-c"><fmt:message key="BANNER_当前位置" bundle="${bundle}"/>：<a href="/public/index"><fmt:message key="BANNER_筑誉首页" bundle="${bundle}"/></a> > <fmt:message key="INDEX_走进筑誉" bundle="${bundle}"/> > <fmt:message key="INDEX_业务格局" bundle="${bundle}"/></div></c:if>
    <c:if test="${param.page == '3'}"><div class="two-loc-c"><fmt:message key="BANNER_当前位置" bundle="${bundle}"/>：<a href="/public/index"><fmt:message key="BANNER_筑誉首页" bundle="${bundle}"/></a> > <fmt:message key="INDEX_走进筑誉" bundle="${bundle}"/> > <fmt:message key="INDEX_发展历程" bundle="${bundle}"/></div></c:if>
    <c:if test="${param.page == '4'}"><div class="two-loc-c"><fmt:message key="BANNER_当前位置" bundle="${bundle}"/>：<a href="/public/index"><fmt:message key="BANNER_筑誉首页" bundle="${bundle}"/></a> > <fmt:message key="INDEX_走进筑誉" bundle="${bundle}"/> > <fmt:message key="INDEX_会长致辞" bundle="${bundle}"/></div></c:if>
    <c:if test="${param.page == '5'}"><div class="two-loc-c"><fmt:message key="BANNER_当前位置" bundle="${bundle}"/>：<a href="/public/index"><fmt:message key="BANNER_筑誉首页" bundle="${bundle}"/></a> > <fmt:message key="INDEX_走进筑誉" bundle="${bundle}"/> > <fmt:message key="INDEX_理事宣言" bundle="${bundle}"/></div></c:if>
    <c:if test="${param.page == '6'}"><div class="two-loc-c"><fmt:message key="BANNER_当前位置" bundle="${bundle}"/>：<a href="/public/index"><fmt:message key="BANNER_筑誉首页" bundle="${bundle}"/></a> > <fmt:message key="INDEX_走进筑誉" bundle="${bundle}"/> > <fmt:message key="INDEX_联系我们" bundle="${bundle}"/></div></c:if>
    <c:if test="${param.page == '7'}"><div class="two-loc-c"><fmt:message key="BANNER_当前位置" bundle="${bundle}"/>：<a href="/public/index"><fmt:message key="BANNER_筑誉首页" bundle="${bundle}"/></a> > <fmt:message key="INDEX_资讯专区" bundle="${bundle}"/> > <fmt:message key="INDEX_企业人才需求" bundle="${bundle}"/></div></c:if>
    <c:if test="${param.page == '8'}"><div class="two-loc-c"><fmt:message key="BANNER_当前位置" bundle="${bundle}"/>：<a href="/public/index"><fmt:message key="BANNER_筑誉首页" bundle="${bundle}"/></a> > <fmt:message key="INDEX_资讯专区" bundle="${bundle}"/> > <fmt:message key="INDEX_筑誉人才库" bundle="${bundle}"/></div></c:if>
    <c:if test="${param.page == '9'}"><div class="two-loc-c"><fmt:message key="BANNER_当前位置" bundle="${bundle}"/>：<a href="/public/index"><fmt:message key="BANNER_筑誉首页" bundle="${bundle}"/></a> > <fmt:message key="INDEX_资讯专区" bundle="${bundle}"/> > <fmt:message key="INDEX_采购供求信息" bundle="${bundle}"/></div></c:if>
    <c:if test="${param.page == '10'}"><div class="two-loc-c"><fmt:message key="BANNER_当前位置" bundle="${bundle}"/>：<a href="/public/index"><fmt:message key="BANNER_筑誉首页" bundle="${bundle}"/></a> > <fmt:message key="INDEX_资讯专区" bundle="${bundle}"/> > <fmt:message key="INDEX_海外工程合作" bundle="${bundle}"/></div></c:if>
    <c:if test="${param.page == '11'}"><div class="two-loc-c"><fmt:message key="BANNER_当前位置" bundle="${bundle}"/>：<a href="/public/index"><fmt:message key="BANNER_筑誉首页" bundle="${bundle}"/></a> > <fmt:message key="INDEX_资讯专区" bundle="${bundle}"/> > <fmt:message key="INDEX_建筑产业化合作" bundle="${bundle}"/></div></c:if>
    <c:if test="${param.page == '12'}"><div class="two-loc-c"><fmt:message key="BANNER_当前位置" bundle="${bundle}"/>：<a href="/public/index"><fmt:message key="BANNER_筑誉首页" bundle="${bundle}"/></a> > <fmt:message key="INDEX_资讯专区" bundle="${bundle}"/> > <fmt:message key="INDEX_养老地产合作" bundle="${bundle}"/></div></c:if>
    <c:if test="${param.page == '13'}"><div class="two-loc-c"><fmt:message key="BANNER_当前位置" bundle="${bundle}"/>：<a href="/public/index"><fmt:message key="BANNER_筑誉首页" bundle="${bundle}"/></a> > <fmt:message key="INDEX_资讯专区" bundle="${bundle}"/> > <fmt:message key="INDEX_新材料新技术" bundle="${bundle}"/></div></c:if>
    <c:if test="${param.page == '14'}"><div class="two-loc-c"><fmt:message key="BANNER_当前位置" bundle="${bundle}"/>：<a href="/public/index"><fmt:message key="BANNER_筑誉首页" bundle="${bundle}"/></a> > <fmt:message key="INDEX_资讯专区" bundle="${bundle}"/> > <fmt:message key="INDEX_建筑产业化" bundle="${bundle}"/></div></c:if>
    <c:if test="${param.page == '15'}"><div class="two-loc-c"><fmt:message key="BANNER_当前位置" bundle="${bundle}"/>：<a href="/public/index"><fmt:message key="BANNER_筑誉首页" bundle="${bundle}"/></a> > <fmt:message key="INDEX_资讯专区" bundle="${bundle}"/> > <fmt:message key="INDEX_绿色建筑" bundle="${bundle}"/></div></c:if>
    <c:if test="${param.page == '16'}"><div class="two-loc-c"><fmt:message key="BANNER_当前位置" bundle="${bundle}"/>：<a href="/public/index"><fmt:message key="BANNER_筑誉首页" bundle="${bundle}"/></a> > <fmt:message key="INDEX_资讯专区" bundle="${bundle}"/> > <fmt:message key="INDEX_BIM技术" bundle="${bundle}"/></div></c:if>
    <c:if test="${param.page == '17'}"><div class="two-loc-c"><fmt:message key="BANNER_当前位置" bundle="${bundle}"/>：<a href="/public/index"><fmt:message key="BANNER_筑誉首页" bundle="${bundle}"/></a> > <fmt:message key="INDEX_资讯专区" bundle="${bundle}"/> > <fmt:message key="INDEX_详细信息" bundle="${bundle}"/></div></c:if>
</div>